services:
  ros1d:
    image: ros1d
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ros1d
    stop_signal: SIGINT
    network_mode: host
    privileged: true
    stdin_open: true
    tty: true
    user: user
    volumes:
      - /home/tievenr/ros_ws/src:/home/user/ros_ws/src
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    command: /bin/bash